version: '3.8'

services:
  frontend:
    image: cruzcal-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-tier
      - web-tier

  backend:
    image: cruzcal-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "3010:3010"
    networks:
      - app-tier
      - db-tier
    depends_on:
      - "db"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - db-tier

networks:
  app-tier: {}
  web-tier: {}
  db-tier: {}
